version: '3.8'

services:
  # Kafka сервис
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_NAME_INNER: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTER_BROKER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # Zookeeper сервис (необходим для работы Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  # База данных PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_CoffeMenu
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  # Ваше Spring Boot приложение
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_CoffeMenu
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9093
